[build]
  publish = ".next"
  command = "npm install && npm run build"

[context.production]
  branch = "main"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200